config/routes.rb
require "rack/gridfs"

# Use Rails.application.routes.prepend on Rails 3.1.
Rails.application.routes.draw do
  match "/visits/record.gif" => "concen/visits#record", :as => "record_visit"
  match "/visits/js" => "concen/visits#visit_recorder_js", :as => "visit_recorder_js"

  scope :constraints => {:subdomain => "concen"}, :module => "concen", :as => "concen"  do
    get "signout" => "sessions#destroy", :as => "signout"
    get "signin" => "sessions#new", :as => "signin"
    get "signup" => "users#new", :as => "signup"

    resources :users do
      collection do
        get :new_invite
        post :invite
        get :new_reset_password
        post :reset_password
      end
      member do
        put :toggle_attribute
      end
    end

    resources :sessions

    resource :status do
      member do
        get :server
        get :counts
      end
    end

    resource :traffic do
      member do
        get :visits_counts
        get :pages
        get :referrals
      end
    end

    resource :performance do
      member do
        get :responses
        get :runtimes
      end
    end

    resources :pages do
      collection do
        put :sort
      end

      resources :grid_files do
        collection do
          post :upload
        end
      end
    end

    root :to => "statuses#show"
  end

  begin
    mount Rack::GridFS::Endpoint.new(:db => Mongoid.database, :lookup => :path, :expires => 315360000), :at => "gridfs"
  rescue; end;
end

app/controllers/concen/application_controller.rb
module Concen
  class ApplicationController < ActionController::Base
    protect_from_forgery

    before_filter :set_concen

    helper_method :current_concen_user, :authenticate_concen_user

    protected

    def set_concen
      @concen = true
    end

    def current_concen_user
      @current_concen_user ||= User.where(:auth_token => cookies[:auth_token]).first if cookies[:auth_token]
    end

    def authenticate_concen_user
      redirect_to concen_signin_path unless current_concen_user
    end
  end
end

app/controllers/concen/grid_files_controller.rb
module Concen
  class GridFilesController < Concen::ApplicationController
    def new
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.build
    end

    def create
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.build
      filename = params[:filename]
      if ["css", "js"].include?(params[:file_type])
        unless MIME::Types.type_for(filename).first.to_s.include?(params[:file_type])
          filename << "." + params[:file_type]
        end
      end
      if @grid_file.store("", filename)
        content = render_to_string(:partial => "concen/pages/files")
        render :json => {:success => true, :content => content}
      else
        render :json => {:success => false}
      end
    end

    def edit
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.find(params[:id])
    end

    def update
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.find(params[:id])
      if @grid_file.store(params[:concen_grid_file_page], @grid_file.original_filename)
        redirect_to edit_concen_page_grid_file_path(@page, @grid_file)
      else
        render :edit
      end
    end

    def destroy
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.find(params[:id])
      respond_to do |format|
        if @grid_file.destroy
          format.html { redirect_to edit_concen_page_path(@page) }
          format.json { render :json => {:success => true} }
        else
          format.html { redirect_to edit_concen_page_path(@page) }
          format.json { render :json => {:success => false} }
        end
      end
    end

    def upload
      # logger.info { "----#{env['rack.input']}" }
      # logger.info { "----#{env['HTTP_X_FILE_NAME']}" }
      # logger.info { "----#{env['CONTENT_TYPE']}" }
      @page = Page.find(params[:page_id])
      @grid_file = @page.grid_files.build
      if env["rack.input"]
        file = env["rack.input"]
        filename = CGI::unescape(env["HTTP_X_FILE_NAME"])
      else
        file = params[:qqfile].read
        filename = params[:qqfile].original_filename
      end
      if @grid_file.store(file, filename)
        content = render_to_string(:partial => "concen/pages/files")
        render :json => {:success => true, :content => content}
      end
    end
  end
end

app/controllers/concen/pages_controller.rb
module Concen
  class PagesController < Concen::ApplicationController
    before_filter :authenticate_concen_user

    def index
      @page_title = "Pages"
      @page = Page.where(:level => 0).first
    end

    def new
      if params[:parent_id]
        @page = Page.find(params[:parent_id]).children.build
      else
        @page = Page.new
      end
    end

    def create
      @page = Page.new(params[:concen_page])
      @page.authors = [current_concen_user.username]
      if @page.save
        redirect_to(edit_concen_page_path(@page), :notice => "Page was successfully created.")
      else
        render :new
      end
    end

    def edit
      @page = Page.find(params[:id])
      unless current_concen_user.full_control || @page.authors_as_user.include?(current_concen_user)
        flash[:notice] = "Only author can edit page."
        redirect_to concen_pages_path
      end
    end

    def update
      @page = Page.find(params[:id])
      if current_concen_user.full_control || @page.authors_as_user.include?(current_concen_user)
        if @page.update_attributes(params[:concen_page])
          redirect_to(edit_concen_page_path(@page), :notice => "Page was successfully created.")
        else
          render :edit
        end
      else
        render :edit, :notice => "Only author can modify page content."
      end
    end

    def destroy
      if current_concen_user.full_control || @page.authors_as_user.include?(current_concen_user)
        @page = Page.find(params[:id])
        @page.destroy
        redirect_to concen_pages_path
      else
        flash[:notice] = "Only author can delete page."
        redirect_to concen_pages_path
      end
    end

    def sort
      if params[:page]
        if current_concen_user.full_control
          child_count = {}
          params[:page].each do |key, value|
            if value == "root"
              root = Page.find(key)
              root.parent_id = nil
              root.level = 0
              root.save
            else
              child = Page.find(key)
              parent = Page.find(value)
              child.parent_id = parent.id
              child.level = parent.level + 1
              if child_count[value]
                child.position = child_count[value] + 1
                child_count[value] += 1
              else
                child.position = 1
                child_count[value] = 1
              end
              child.save
            end
          end
          render :json => {:success => true}
        else
          render :json => {:success => false, :message => "Only user with full control can sort pages."}
        end
      end
    end
  end
end

app/controllers/concen/performances_controller.rb
module Concen
  class PerformancesController < Concen::ApplicationController
    def show
      @page_title = "Performance"
    end

    def responses
      @stats = {}
      @stats[:total_runtime] = Response.where(:created_at.gte => Time.now - 1.hour).asc(:created_at).map do |response|
        [(response.created_at.utc.to_f + response.created_at.utc_offset)*1000, response.total_runtime]
      end
      @stats[:view_runtime] = Response.where(:created_at.gte => Time.now - 1.hour).asc(:created_at).map do |response|
        if response.respond_to?("view_runtime")
          [(response.created_at.utc.to_f + response.created_at.utc_offset)*1000, response.view_runtime]
        end
      end
      @stats[:mongo_runtime] = Response.where(:created_at.gte => Time.now - 1.hour).asc(:created_at).map do |response|
        if response.respond_to?("mongo_runtime")
          [(response.created_at.utc.to_f + response.created_at.utc_offset)*1000, response.mongo_runtime]
        end
      end

      respond_to do |format|
        format.json { render :json => @stats }
      end
    end

    def runtimes
      @runtimes_stats = Response.aggregate_average_runtime(:type => params[:type])
      respond_to do |format|
        format.html { render :partial => "concen/performances/runtimes" }
      end
    end
  end
end

app/controllers/concen/sessions_controller.rb
module Concen
  class SessionsController < Concen::ApplicationController
    def new
      if User.all.any?
        render
      else
        redirect_to new_concen_user_path
      end
    end

    def create
      user = User.where(:username => /#{params[:username]}/i).first

      if user && user.authenticate(params[:password])
        cookies.permanent[:auth_token] = user.auth_token
        redirect_to concen_root_path, :notice => "You have successfully signed in!"
      else
        flash.now.alert = "Invalid email or password"
        render "new"
      end
    end

    def destroy
      cookies.delete(:auth_token)
      redirect_to root_path, :notice => "You have successfully signed out!"
    end
  end
end

app/controllers/concen/statuses_controller.rb
module Concen
  class StatusesController < Concen::ApplicationController
    before_filter :authenticate_concen_user

    def show
      @page_title = "Status"
      render
    end

    def counts
      respond_to do |format|
        format.json {
          render :json => {:pages => Page.count, :users => User.count}
        }
      end
    end

    def server
      processor_stat = []
      memory_stat = []
      @server_stats = {}
      if RUBY_PLATFORM.downcase.include?("darwin")
        top = `top -l 1 -pid 0`.split(/\n+/)
        if top.present?
          processor_stat = top[3].scan(/[0-9]+\.\d+/)
          memory_stat = top[6].scan(/[0-9]\d+/)
          @server_stats = {
            :processor => {:user => processor_stat[0], :sys => processor_stat[1], :idle => processor_stat[2]},
            :memory => {:wired => memory_stat[0], :active => memory_stat[1], :inactive => memory_stat[2], :used => memory_stat[3], :free => memory_stat[4]}
          }
        end
      elsif RUBY_PLATFORM.downcase.include?("linux")
        top = `top -b -n 1 -p 0`.split(/\n+/)
        if top.present?
          processor_stat = top[2].scan(/[0-9]+\.\d+/)
          memory_stat = top[3].scan(/[0-9]\d+/)
          @server_stats = {
            :processor => {:user => processor_stat[0], :sys => processor_stat[1], :idle => processor_stat[3]},
            :memory => {:total => memory_stat[0].to_i/1024, :used => memory_stat[1].to_i/1024, :free => memory_stat[2].to_i/1024}
          }
        end
      end
      uptime_array = `uptime`.split("up")[1].strip.split("user")[0].split(","); uptime_array.delete_at(uptime_array.length - 1)
      if uptime_array.present?
        uptime = uptime_array.join(",")
        @server_stats[:uptime] = uptime
      end

      @mongodb_stats = Mongoid.database.stats

      begin
        @mongodb_grid_fs_stats = Mongoid.database.collection("fs.chunks").stats["storageSize"]
      rescue
        @mongodb_grid_fs_stats = 0
      end
      respond_to do |format|
        format.html { render :partial => "concen/statuses/server" }
      end
    end
  end
end

app/controllers/concen/traffics_controller.rb
module Concen
  class TrafficsController < Concen::ApplicationController
    before_filter :authenticate_concen_user

    # Supports OS X and Linux, require top command.
    #   @current_month_visits = Statistic.visits_for_current :month
    # Real time visits
    # Historical statistics
    # Month: visits
    def show
      @page_title = "Traffic"
    end

    def visits_counts
      if @stats = Visit::Page.aggregate_count_by_time(:hour => params[:hour], :precision => "millisecond")
        # Readjust timestamp because flot graph doesn't handle time zone.
        @stats.map! do |s|
          time = Time.zone.at s[0]/1000
          [(time.utc.to_i + time.utc_offset)*1000, s[1]]
        end
      end
      respond_to do |format|
        format.json { render :json => @stats }
      end
    end

    def pages
      @pages_stats = Visit::Page.aggregate_count_by_url(:limit => 6)
      respond_to do |format|
        format.html { render :partial => "concen/traffics/pages" }
      end
    end

    def referrals
      @referrals_stats = Visit::Referral.aggregate_count_by_domain(:limit => 6)
      respond_to do |format|
        format.html { render :partial => "concen/traffics/referrals" }
      end
    end
  end
end

app/controllers/concen/users_controller.rb
module Concen
  class UsersController < Concen::ApplicationController
    before_filter :authenticate_concen_user, :except => [:new, :edit, :update, :create, :new_reset_password, :reset_password]

    def index
      @page_title = "Users"
      @users = User.all
    end

    def new
      if User.all.any?
        redirect_to root_path
      else
        @user = User.new
      end
    end

    def create
      if !User.all.any? || (current_concen_user && current_concen_user.full_control)
        @user = User.new(params[:concen_user])
        @user.full_control = true
        if @user.save
          redirect_to(concen_users_path, :notice => "User was successfully created.")
        else
          render :new
        end
      end
    end

    def edit
      if params[:password_reset_token]
        @user = User.where(:password_reset_token => params[:password_reset_token]).first
      elsif params[:invitation_token]
        @user = User.where(:invitation_token => params[:invitation_token]).first
      else
        @page_title = "Settings"
        @user = current_concen_user
      end
      redirect_to concen_signin_path unless @user
    end

    def update
      if params[:concen_user][:password_reset_token]
        @user = User.where(:password_reset_token => params[:concen_user][:password_reset_token]).first
        authenticated = true if @user.password_reset_sent_at > 2.hours.ago
      elsif params[:concen_user][:invitation_token]
        @user = User.where(:invitation_token => params[:concen_user][:invitation_token]).first
        authenticated = true if @user.invitation_sent_at > 24.hours.ago
      else
        @user = current_concen_user
        authenticated = true if @user.authenticate(params[:concen_user].delete(:current_password))
      end
      if @user && authenticated
        if @user.update_attributes(params[:concen_user])
          redirect_to edit_concen_user_path @user
        else
          render :edit
        end
      else
        flash.now.alert = "Invalid password."
        render :edit
      end
    end

    def destroy
      if current_concen_user.full_control
        @user = User.find(params[:id])
        @user.destroy
        redirect_to concen_users_path
      else
        flash[:notice] = "Only user with full control can delete a user."
        redirect_to concen_users_path
      end
    end

    def toggle_attribute
      respond_to do |format|
        if current_concen_user.full_control
          @user = User.find(params[:id])
          @user.write_attribute(params[:attribute].to_sym, !@user.read_attribute(params[:attribute].to_sym))
          @user.save
          format.json { render :json => {:success => true} }
        else
          format.json { render :json => {:success => false, :message => "Only user with full control can toggle attribute."} }
        end
      end
    end

    def new_invite
      if current_concen_user.full_control
        @user = User.new
      else
        redirect_to(concen_users_path, :notice => "Only user with full control can invite.")
      end
    end

    def invite
      if current_concen_user.full_control
        @user = User.send_invitation params[:concen_user][:email]
        redirect_to concen_users_path, :notice => "Invitation has been sent."
      else
        redirect_to concen_users_path, :notice => "Only user with full control can invite."
      end
    end

    def new_reset_password
      @user = User.new
    end

    def reset_password
      @user = User.where(:email => params[:concen_user][:email]).first
      @user.send_password_reset
      redirect_to concen_signin_path, :notice => "Password reset instruction has been sent."
    end
  end
end

app/helpers/concen/application_helper.rb
module Concen
  module ApplicationHelper
  end
end

app/helpers/concen/pages_helper.rb
module Concen
  module PagesHelper

  end
end

app/helpers/concen/visits_helper.rb
module Concen
  module VisitsHelper
  end
end

app/views/concen/pages/_file_list.erb
<ul>
  <% files.each_with_index do |file, index| %>
    <li>
      <%= link_to "#{file.original_filename} (#{number_to_human_size(file.size)})", file.url(root_url), :class => "filename", "data-path" => file.path %>
      <% if file.text? %>
        <%= link_to "Edit", edit_concen_page_grid_file_path(file.page, file) %>
      <% end %>
      <%= link_to "Delete", concen_page_grid_file_path(file.page, file), :class => "delete" %>
    </li>
  <% end %>
</ul>

app/views/concen/pages/_files.erb
<div class="files">
  <div class="stylesheets">
    <h3>
      <span>Stylesheets</span>
      <%= link_to "New", concen_page_grid_files_path(@page, :file_type => "css"), :class => "link-button new-file" %>
    </h3>
    <% if @page.stylesheets.any? %>
      <%= render :partial => "concen/pages/file_list", :locals => {:files => @page.stylesheets} %>
    <% end %>
  </div>
  <div class="javascripts">
    <h3>
      <span>JavaScripts</span>
      <%= link_to "New", concen_page_grid_files_path(@page, :file_type => "js"), :class => "link-button new-file" %>
    </h3>
    <% if @page.javascripts.any? %>
      <%= render :partial => "concen/pages/file_list", :locals => {:files => @page.javascripts} %>
    <% end %>
  </div>
  <% if @page.images.any? %>
    <div class="images">
      <h3>Images</h3>
      <%= render :partial => "concen/pages/file_list", :locals => {:files => @page.images} %>
    </div>
  <% end %>
  <% if @page.others.any? %>
    <div class="others">
      <h3>Others</h3>
      <%= render :partial => "concen/pages/file_list", :locals => {:files => @page.others} %>
    </div>
  <% end %>
</div>

app/views/concen/pages/_form.html.erb
<%= form_for @page, {:html => {:class => "with-text-editor #{'wide' if !@page.persisted?}"}} do |f| %>
  <% if @page.errors.any? %>
    <div id="errorExplanation">
      <h3><%= "#{pluralize(@page.errors.count, "error")} prohibited this parent from being saved:" %></h3>
      <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field text-editor">
    <div class="border">
      <div id="text-editor"></div>
    </div>
  </div>
  <%= f.text_area :raw_text, :class => "text-editor-content hidden" %>
  <%= f.hidden_field :parent_id %>
  <div class="actions flush">
    <%= f.submit "Save" %>
    <% if @page.persisted? %>
      <%= link_to "Delete", concen_page_path(@page), :method => :delete %>
    <% end %>
    <%= link_to "Cancel", concen_pages_path %>
  </div>
<% end %>

app/views/concen/pages/_nested_list.html.erb
<% if root && page.level == 0 %>
  <% children = [page] %>
<% else %>
  <% children = Concen::Page.where(:parent_id => page.id).asc(:position) %>
<% end %>

<ul class="<%= 'pages' if children.first.level == 0 %>" data-level="<%= children.first.level %>">
  <% for child in children %>
    <li data-id="<%= "page-" + child.id.to_s %>">
      <p class="<%= 'author' if child.authors_as_user.map(&:_id).include? current_concen_user.id %>">
        <span class="handle"></span>
        <%= link_to child.title, edit_concen_page_path(child), :class => "title" %>
        <%= link_to "Add", new_concen_page_path(:parent_id => child.id), :class => "link-button hidden" %>
        <%= link_to "Edit", edit_concen_page_path(child), :class => "link-button hidden" %>
        <%= link_to "Delete", concen_page_path(child), :method => :delete, :confirm => "Are you sure?", :class => "link-button hidden" %>
      </p>
      <% if Concen::Page.where(:parent_id => child.id).count > 0 %>
        <%= render :partial => "nested_list", :locals => {:page => child, :root => false} %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/concen/pages/edit.html.erb
<% content_for :head_javascripts do %>
  <%= javascript_include_tag "concen/pages" %>
<% end %>

<div id="content">
  <h1>Edit Page</h1>
  <%= render "form" %>
  <div id="file-manager">
    <div class="border">
      <div id="file-uploader" data-upload-path="<%= upload_concen_page_grid_files_path(@page) %>">
        <noscript>
          <p>Please enable JavaScript to use file uploader.</p>
        </noscript>
      </div>
      <%= render "files" %>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/concen/pages/index.html.erb
<% content_for :head_javascripts do %>
  <%= javascript_include_tag "concen/pages" %>
<% end %>

<div id="content">
  <h1>
    <span>Pages</span><% unless @page %><%= link_to "New Page", new_concen_page_path, :class => "link-button" %><% end %>
  </h1>
  <% if @page %>
    <%= render :partial => "nested_list", :locals => {:page => @page, :root => true} %>
  <% end %>
</div>

app/views/concen/pages/new.html.erb
<% content_for :head_javascripts do %>
  <%= javascript_include_tag "concen/pages" %>
<% end %>

<div id="content">
  <h1>New Page</h1>
  <div class="clearfix">
    <%= render "form" %>
  </div>
</div>